version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
      - ./api/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  front:
    build: ./front
    working_dir: /app
    volumes:
      - ./front:/app
    ports:
      - "80:80"
    tty: true
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/pc_specs_db 
    command: bash -c "npm install && node index.js"